### PR TITLE
Update AWS config to fix SSO login

### LINKED ISSUE #52: SSO authentication is not supported
## Describe the Bug
The new SSO format doesn't require sso_region and sso_start_url for every profile. Currently, it throws a following error:
```
│ Error: error configuring Terraform AWS Provider: loading configuration: profile "<redacted>" is configured to use SSO but is missing required configuration: sso_region, sso_start_url
│ 
│   with provider["registry.terraform.io/cloudposse/awsutils"],
│   on <empty> line 0:
│   (source code not available)

```

That's described over here: https://github.com/hashicorp/terraform-provider-aws/issues/28263#issuecomment-1428052544 and fixed by updating AWS SDK like in this commit: https://github.com/hashicorp/terraform-provider-aws/commit/bf5aed5bc8b73db62b3fe1b6d4e76dd4408a16b0

## Expected Behavior
The provider should support the new SSO configuration syntax

### PR DESCRIPTION
**Pull request by petrzjunior**
## what
* update aws/aws-sdk-go-v2/config and aws/aws-sdk-go-v2/credentials to the newest versions

## why
* old version does not allow SSO login to AWS and crashes, see #52

> Error: error configuring Terraform AWS Provider: loading configuration: profile "profile" is configured to use SSO but is missing required configuration: sso_region, sso_start_url

## references
* closes  #52
* relevant discussion in AWS provier: https://github.com/hashicorp/terraform-provider-aws/issues/28263#issuecomment-1428052544

P.S. This is my first ever Go PR, feel free to correct me. This is currently a blocking issue for me so I am trying to push it.

### CODE REVIEW

**Comment by rafaljanicki** [comment]
Any chance to get this merged @mcalhoun ?

**Comment by sebrichards** [comment]
Perhaps @Nuru you'd be able to review this?

**Comment by petrzjunior** [comment]
Btw. I have compiled it locally and been using it successfully for 2 months without any problems.

**Comment by miljanic** [comment]
@aknysh @hans-d Do you guys have a plan for when this version will be available on the terraform registry?

**Comment by hans-d** [comment]
We're currently checking - as some repos dont seem to be having a working auto-update-me for the registry.

**Comment by rafaljanicki** [comment]
Any updates here @hans-d ? I see that the TF registry still has the old version

**Pull request merged**
